### ISSUE TITLE
Just downloaded, not loading any content?

### ISSUE THREAD

**Issue by Austin1** [kaangiray26/geddit-app#15]
I saw a new version was just posted 2 hours ago. I'm a fresh new user, never installed, and after downloading and opening, I can't get any content to come through?

https://github.com/kaangiray26/geddit-app/assets/341408/2f5214cd-6706-41d6-8716-c65df96db00c

**Comment by Austin1** [comment]
I hit clear hidden posts and it seems to show some content now. Might be good to change that default though. 

Can you login to your account?

**Comment by kaangiray26** [comment]
Thanks for pointing this out, I can also confirm the bug.  
I've released a [new version](https://github.com/kaangiray26/geddit-app/releases/tag/v1.2) that fixes this problem.

And for the login part, because Geddit does not use Reddit's API, it is not possible to login to your account, sorry. This is just for public viewing.
